name: Release

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify Node.js version compatible with your project

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: ['main', staging]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate with the GitHub API
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # NPM token if you are publishing to npm

      # Optionally, print the new version for debugging
      - name: Output version
        run: echo "Released version is ${{ steps.semantic.outputs.new_release_version }}"
