
name: Release and Update Changelog

on:
  push:
    branches:
      - main
      - staging

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: ['main', staging]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}